/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VectofixRouteImport } from './routes/vectofix'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VectofixIndexRouteImport } from './routes/vectofix.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VectofixBlogRouteImport } from './routes/vectofix.blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as VectofixBlogSlugRouteImport } from './routes/vectofix.blog.$slug'

const VectofixRoute = VectofixRouteImport.update({
  id: '/vectofix',
  path: '/vectofix',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixIndexRoute = VectofixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VectofixRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixBlogRoute = VectofixBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => VectofixRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixBlogSlugRoute = VectofixBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VectofixBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/vectofix': typeof VectofixRouteWithChildren
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/blog': typeof VectofixBlogRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/vectofix/': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/blog': typeof VectofixBlogRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/vectofix': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/vectofix': typeof VectofixRouteWithChildren
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/blog': typeof VectofixBlogRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/vectofix/': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/privacy'
    | '/vectofix'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/vectofix/blog'
    | '/blog/'
    | '/vectofix/'
    | '/vectofix/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/privacy'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/vectofix/blog'
    | '/blog'
    | '/vectofix'
    | '/vectofix/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/privacy'
    | '/vectofix'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/vectofix/blog'
    | '/blog/'
    | '/vectofix/'
    | '/vectofix/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  VectofixRoute: typeof VectofixRouteWithChildren
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vectofix': {
      id: '/vectofix'
      path: '/vectofix'
      fullPath: '/vectofix'
      preLoaderRoute: typeof VectofixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/': {
      id: '/vectofix/'
      path: '/'
      fullPath: '/vectofix/'
      preLoaderRoute: typeof VectofixIndexRouteImport
      parentRoute: typeof VectofixRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/blog': {
      id: '/vectofix/blog'
      path: '/blog'
      fullPath: '/vectofix/blog'
      preLoaderRoute: typeof VectofixBlogRouteImport
      parentRoute: typeof VectofixRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/blog/$slug': {
      id: '/vectofix/blog/$slug'
      path: '/$slug'
      fullPath: '/vectofix/blog/$slug'
      preLoaderRoute: typeof VectofixBlogSlugRouteImport
      parentRoute: typeof VectofixBlogRoute
    }
  }
}

interface VectofixBlogRouteChildren {
  VectofixBlogSlugRoute: typeof VectofixBlogSlugRoute
}

const VectofixBlogRouteChildren: VectofixBlogRouteChildren = {
  VectofixBlogSlugRoute: VectofixBlogSlugRoute,
}

const VectofixBlogRouteWithChildren = VectofixBlogRoute._addFileChildren(
  VectofixBlogRouteChildren,
)

interface VectofixRouteChildren {
  VectofixBlogRoute: typeof VectofixBlogRouteWithChildren
  VectofixIndexRoute: typeof VectofixIndexRoute
}

const VectofixRouteChildren: VectofixRouteChildren = {
  VectofixBlogRoute: VectofixBlogRouteWithChildren,
  VectofixIndexRoute: VectofixIndexRoute,
}

const VectofixRouteWithChildren = VectofixRoute._addFileChildren(
  VectofixRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  VectofixRoute: VectofixRouteWithChildren,
  ApiSubscribeRoute: ApiSubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
