/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VectofixRouteImport } from './routes/vectofix'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VectofixIndexRouteImport } from './routes/vectofix.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VectofixPrivacyRouteImport } from './routes/vectofix.privacy'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiDownloadsRouteImport } from './routes/api/downloads'
import { Route as VectofixBlogIndexRouteImport } from './routes/vectofix.blog.index'
import { Route as VectofixBlogSlugRouteImport } from './routes/vectofix.blog.$slug'

const VectofixRoute = VectofixRouteImport.update({
  id: '/vectofix',
  path: '/vectofix',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixIndexRoute = VectofixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VectofixRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixPrivacyRoute = VectofixPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => VectofixRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsRoute = ApiDownloadsRouteImport.update({
  id: '/api/downloads',
  path: '/api/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const VectofixBlogIndexRoute = VectofixBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => VectofixRoute,
} as any)
const VectofixBlogSlugRoute = VectofixBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => VectofixRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vectofix': typeof VectofixRouteWithChildren
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/privacy': typeof VectofixPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/vectofix/': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
  '/vectofix/blog/': typeof VectofixBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/privacy': typeof VectofixPrivacyRoute
  '/blog': typeof BlogIndexRoute
  '/vectofix': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
  '/vectofix/blog': typeof VectofixBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vectofix': typeof VectofixRouteWithChildren
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/vectofix/privacy': typeof VectofixPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/vectofix/': typeof VectofixIndexRoute
  '/vectofix/blog/$slug': typeof VectofixBlogSlugRoute
  '/vectofix/blog/': typeof VectofixBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/privacy'
    | '/terms'
    | '/vectofix'
    | '/api/downloads'
    | '/api/subscribe'
    | '/api/track'
    | '/blog/$slug'
    | '/vectofix/privacy'
    | '/blog/'
    | '/vectofix/'
    | '/vectofix/blog/$slug'
    | '/vectofix/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/privacy'
    | '/terms'
    | '/api/downloads'
    | '/api/subscribe'
    | '/api/track'
    | '/blog/$slug'
    | '/vectofix/privacy'
    | '/blog'
    | '/vectofix'
    | '/vectofix/blog/$slug'
    | '/vectofix/blog'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/privacy'
    | '/terms'
    | '/vectofix'
    | '/api/downloads'
    | '/api/subscribe'
    | '/api/track'
    | '/blog/$slug'
    | '/vectofix/privacy'
    | '/blog/'
    | '/vectofix/'
    | '/vectofix/blog/$slug'
    | '/vectofix/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VectofixRoute: typeof VectofixRouteWithChildren
  ApiDownloadsRoute: typeof ApiDownloadsRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiTrackRoute: typeof ApiTrackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vectofix': {
      id: '/vectofix'
      path: '/vectofix'
      fullPath: '/vectofix'
      preLoaderRoute: typeof VectofixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/': {
      id: '/vectofix/'
      path: '/'
      fullPath: '/vectofix/'
      preLoaderRoute: typeof VectofixIndexRouteImport
      parentRoute: typeof VectofixRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/privacy': {
      id: '/vectofix/privacy'
      path: '/privacy'
      fullPath: '/vectofix/privacy'
      preLoaderRoute: typeof VectofixPrivacyRouteImport
      parentRoute: typeof VectofixRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads': {
      id: '/api/downloads'
      path: '/api/downloads'
      fullPath: '/api/downloads'
      preLoaderRoute: typeof ApiDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectofix/blog/': {
      id: '/vectofix/blog/'
      path: '/blog'
      fullPath: '/vectofix/blog/'
      preLoaderRoute: typeof VectofixBlogIndexRouteImport
      parentRoute: typeof VectofixRoute
    }
    '/vectofix/blog/$slug': {
      id: '/vectofix/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/vectofix/blog/$slug'
      preLoaderRoute: typeof VectofixBlogSlugRouteImport
      parentRoute: typeof VectofixRoute
    }
  }
}

interface VectofixRouteChildren {
  VectofixPrivacyRoute: typeof VectofixPrivacyRoute
  VectofixIndexRoute: typeof VectofixIndexRoute
  VectofixBlogSlugRoute: typeof VectofixBlogSlugRoute
  VectofixBlogIndexRoute: typeof VectofixBlogIndexRoute
}

const VectofixRouteChildren: VectofixRouteChildren = {
  VectofixPrivacyRoute: VectofixPrivacyRoute,
  VectofixIndexRoute: VectofixIndexRoute,
  VectofixBlogSlugRoute: VectofixBlogSlugRoute,
  VectofixBlogIndexRoute: VectofixBlogIndexRoute,
}

const VectofixRouteWithChildren = VectofixRoute._addFileChildren(
  VectofixRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VectofixRoute: VectofixRouteWithChildren,
  ApiDownloadsRoute: ApiDownloadsRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiTrackRoute: ApiTrackRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
